version: '3.8'

services:
  alger-music-player:
    build:
      context: .
      dockerfile: Dockerfile
    image: alger-music-player:latest
    container_name: alger-music-player
    ports:
      - "5173:5173"    # 前端开发服务器端口
      - "3000:3000"    # API 端口
    volumes:
      - "./data:/data"  # 使用本地 ./data 目录
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    networks:
      - alger-music-network

networks:
  alger-music-network:
    driver: bridge
