version: '3.8'

services:
  alger-music-player:
    volumes:
      # 开发时直接挂载本地代码目录（如果存在）
      - "./frontend:/app/frontend:cached"    # 前端代码热重载
      - "./api:/app/api:cached"              # API代码热重载
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # 支持文件变化检测
