version: '3.8'

services:
  alger-music-player:
    build:
      context: .
      dockerfile: Dockerfile
    image: alger-music-player:latest
    container_name: alger-music-player
    ports:
      - "3000:80"      # 前端访问端口
      - "3001:3000"    # API 访问端口
    volumes:
      - "./data:/data"  # 使用本地 ./data 目录
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - alger-music-network

networks:
  alger-music-network:
    driver: bridge
